### PR TITLE
Added the Discovery Client into the SharingClient dll.

### PR DESCRIPTION
**Pull request by alexdrenea**
Enabling Network Discovery in SharingClient similar to Profiler as per #25

### CODE REVIEW

**Comment by NeerajW** [comment]
@alexdrenea have you made sure that this does not break the Unity side binaries?
Please test out the HoloToolkit-Unity sharing scene as well with these changes since this is updating SharingClient.dll.

**Comment by alexdrenea** [comment]
I've tested that sharing works with my app not with the Scharing scene. I will test it today.
I'm a but confused about the folders though, what's the difference between WSA and x86/x64 in the Sharing/Plugins folder?

**Comment by NeerajW** [comment]
When you are done compiling:
1. <your HoloToolkit path>\Sharing\Src\GeneratedInterface\CSharpAPI - these are the files that end up in the SDK folder in <HoloToolkit-Unity path>\Assets\HoloToolkit\Sharing\Scripts\SDK. The ones that don't exist in there should be deleted from your copy. You might have to edit an auto generated PINVOKE file since some functionalities are not exposed in the unity repo.

2. For binaries:
<your HoloToolkit path>\Sharing\Src\bin\Release\x64\SharingService binaries into https://github.com/Microsoft/HoloToolkit-Unity/tree/master/External/HoloToolkit/Sharing/Server 

<your HoloToolkit path>\Sharing\Src\bin\Release\x64\ClientUniversalCSharp binaries into WSA folder
https://github.com/Microsoft/HoloToolkit-Unity/tree/master/Assets/HoloToolkit/Sharing/Plugins/WSA 

<your HoloToolkit path>\Sharing\Src\bin\Release\x64\ClientWindowsCSharp binaries into https://github.com/Microsoft/HoloToolkit-Unity/tree/master/Assets/HoloToolkit/Sharing/Plugins/x64

**Comment by alexdrenea** [comment]
Hi @NeerajW !

Thanks for the detailed instructions. and confirming that the Plugins-WSA folder is the output of ClientUniversalCharp and the Plugins-root is the output of ClientWindowsCharp . 
As I didn't change the Server component, I don't know that I should be updating that. 

I checked the changes in the PINVOKE file and it only contains functions related to Discovery. Please advise if you think some of those should be removed although I don't know if it does any harm if they are there.

In any case, I made all the updates and tested with the sharing scene and everything seems to be working. 

Should I get a PR  in for the HoloToolkit-Unity repo as well?

**Comment by NeerajW** [comment]
@alexdrenea yes if you have verified the test scene then go ahead. If you did not make any changes to SharingServer then no need to update it.

**Comment by alexdrenea** [comment]
Thanks @NeerajW . submitted PR as well. 
I recommend that they both get merged (this one and the one in the Unity repo) at the same time so there's no confusion on where the libraries came from.

**Comment by jwittner** [comment]
Worked well!

**Comment by jwittner** [comment]
@alexdrenea  Now that I've merged this I tried to build again from master and I'm getting errors from both SessionManager.UI projects about 

>`17>C:\Users\jowitt\Source\HoloToolkit\Sharing\Src\generatedinterface\csharpapi\SharingClientPINVOKE.cs(1533,126,1533,149): error CS0246: The type or namespace name 'DiscoveryClientListener' could not be found (are you missing a using directive or an assembly reference?)`

Rolling this back, but we'll need to fix this ASAP cause I moved the HTK-Unity portion in already and that works fine.

**Comment by jwittner** [comment]
Looks like they were just missing the additional files - PR forthcoming.

**Pull request merged**
