### PR TITLE
Editor spatial understanding

### PR DESCRIPTION
**Pull request by mrbobbybobberson**
This is part of [Microsoft/HoloToolkit-Unity#290](https://github.com/Microsoft/HoloToolkit-Unity/issues/290). Note that this also relates to #57 in that it removes the broken ARM platform from the solution.  If someone takes #57 on, they'll need to add it back.

### CODE REVIEW

**Comment by mrbobbybobberson** [comment]
@jevertt, can you take a look at this?  Thanks!

**Comment by jevertt** [comment]
looks good to me

**Comment by matmuze** [comment]
Hi there, when could this be merged into the main branch ?
Thx, Mat.

**Comment by matmuze** [comment]
Sorry for spamming this PR, but I tried the spatial understanding (SU) "In Unity Editor" on mrbobbybobberson's branch, and I noticed that there is a problem with building the SU mesh in Unity when using "Simulate in Editor". It only capture the SU mesh all around the view frustum (but not inside), at the beginning, and then it does not update the SU anymore (I used a Xbox one controller to move the camera and the SU .dll does not update the mesh although the camera move accross the room).

I confirm that it works fine when using "Remote to device" when testing on an actual Hololens tho.

**Comment by mrbobbybobberson** [comment]
@matmuze , I was noticing similar funny business using ObjectSurfaceObserver and a mesh I saved from my house.  It seems like there's a limitation of the spatial understanding code that keeps it from mapping a whole area unless the surfaces are being updated and changed regularly, which is something the emulator/simulator/ObjectSurfaceObserver don't do.

Perhaps someone can follow up after this basic support gets in and improve the code to remove the limitation.

**Comment by matmuze** [comment]
Should we create an issue/feature request about it ?

Also, I guess a much more useful feature/fix, would be to actually be able to build a spatial understanding (SU) structure (voxel grid) from an arbitrary mesh (not necessarily from a mesh registered in the spatial mapping). 

That way the SU functionality in the DLL would be agnostic of how the room mesh is acquired (emulator, actual lens scanning, or pre-save room mesh), which would be less problematic for usage in the Editor.

That would also be great if that structure could be batched at once, without having to gaze through the entire room manually.

for instance:  
// Async batch of the voxel grid for the entire room at once
BatchSpatialUndestandingRoomInternalStructure(vertices, indices); 

//Fetch the mesh for the entire room at once
GetSpatialUnderstandigMesh(&SUvertices, &SUindices);  

For debug that would be awesome, because we could simply load an arbitrary pre-scanned room mesh, batch the SU voxel grid, and get started with the testing, rather that scanning the entire room manually each time you want to try something out.

Finally, an ultimate feature would be to be able to save this SU voxel grid on the disk, directly from Unity, and reload it afterward without the need to rebake the structure each time.

That last feature would be the icing on the cake of course, but already facilitating SU structure baking, like explained above, would be a HUUUGE win for us, Unity users, because we really value quick prototyping iterations directly from the editor more than anything in the world.

**Comment by mrbobbybobberson** [comment]
@matmuze, I agree, that would speed up my development a ton, too!  It looks like others are interested in it, too.  Check out [HoloToolkit-Unity#188](https://github.com/Microsoft/HoloToolkit-Unity/issues/188).

**Comment by matmuze** [comment]
Well saving the mesh is nice but it does not allow placement and shape queries... I meant saving the internal SU structure which lives inside the DLL...

**Comment by mrbobbybobberson** [comment]
Good point.  I hope you'll take part in that discussion and steer it that way, because that would really be the ultimate development feature.

**Comment by mrbobbybobberson** [comment]
@HodgsonSDAS, thanks for merging [Microsoft/HoloToolkit-Unity#290](https://github.com/Microsoft/HoloToolkit-Unity/issues/290) in.  Can you also merge this in so the source code for the DLL is also in the master branch?  Thanks!

**Comment by HodgsonSDAS** [comment]
I'm not a member of this repository, so someone from MSFT will probably need to do this.

**Comment by mrbobbybobberson** [comment]
Ahh, I see.  @NeerajW, are you able to merge this in?

Sent from my Windows 10 phone

**Pull request merged**
