### PR TITLE
Allow creating persistent sessions from client

### LINKED ISSUE #47: Client has no way to create new Persistent sessions.
Extend NewSessionRequest to support type of session to create.

### PR DESCRIPTION
**Pull request by jwittner**
Fixes #47

### CODE REVIEW

**Comment by jwittner** [comment]
Once this is in I have a branch for HTK-Unity to absorb the HTK changes.

**Comment by jwittner** [comment]
@jheuvel-ms  Should this up the XTools Version?

**Comment by jwittner** [comment]
If I can get this approved, I could add saving of new persistent sessions into #42

**Comment by jwittner** [comment]
Anyone out there have thoughts on this?

**Comment by NeerajW** [comment]
Please update version number and when ready please update HTK-Unity.

**Pull request merged**
