### PR TITLE
Added SharingService lib, absorbed SessionServer source

### LINKED ISSUE #14: SharingServer Library
Is there any reason why SharingServer class cannot be included in the sharing library that the client devices use? Also, did you guys think about a P2P version of the SharingServer (and maybe other classes like the lobby/etc) that would take advantage of the ReplicaManager2 and FullyConnectedMesh2 classes available in Raknet?

I am thinking of using the sharing library for a project that combines Holo and PC/tablet but I'd like to move away from a dedicated server model. How far off am I?

### PR DESCRIPTION
**Pull request by jwittner**
Fixes #14

### CODE REVIEW

**Comment by NeerajW** [comment]
@jwittner tell me a little bit more about your thinking for this one please!

**Comment by jwittner** [comment]
Sure! By making this a lib - all the functionality of the sharing service can be easily embedded in any application. This makes the development of new servers leveraging the functionality easier, but it also make embedding the sharing server logic into applications much easier - which translates to simple P2P sharing.

**Comment by jwittner** [comment]
I'm on the fence about adding DLL projects as well, but it's a bit more work due to the run time versions and that chain of projects that will need to be added. I also don't need it quite at this moment, where as I am in the middle of building out an extended server executable that leverages the sharing code.

**Comment by jwittner** [comment]
@NeerajW Anything else needed for this?

**Pull request merged**
